version: '3.8'

services:
  train:
    build:
      context: .
      dockerfile: Dockerfile.train
    container_name: titanic-training
    volumes:
      - models:/app/models
      - ./kaggle.json:/root/.kaggle/kaggle.json:ro
    environment:
      - PYTHONUNBUFFERED=1
      - KAGGLE_CONFIG_DIR=/root/.kaggle

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: titanic-api
    ports:
      - "8000:8000"
    volumes:
      - models:/app/models
    depends_on:
      train:
        condition: service_completed_successfully
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  models:

